# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-23 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageCharacteristicValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('value_from', models.CharField(blank=True, max_length=200, null=True)),
                ('value_to', models.CharField(blank=True, max_length=200, null=True)),
                ('usage_object_id', models.PositiveIntegerField()),
                ('usage_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_usagecharacteristicvalue_ownership', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='UsageSpecCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_specification_object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('value_type', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('value_from', models.CharField(blank=True, max_length=200, null=True)),
                ('value_to', models.CharField(blank=True, max_length=200, null=True)),
                ('range_interval', models.CharField(blank=True, max_length=200, null=True)),
                ('default', models.NullBooleanField()),
                ('usage_specification_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_usagespeccharacteristic_ownership', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceCallUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateTimeField()),
                ('usage_status', models.CharField(max_length=100)),
                ('originationAddress', models.CharField(max_length=100)),
                ('destinationAddress', models.CharField(max_length=100)),
                ('call_duration', models.DurationField()),
                ('call_type', models.CharField(max_length=100)),
                ('party_roles', gm2m.fields.GM2MField(related_name='usage_party_roles', through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk'))),
                ('product_prices', models.ManyToManyField(blank=True, to='product.ProductPrice')),
                ('usage_specification', gm2m.fields.GM2MField(related_name='usage_usage_specification', through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk'))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='usagecharacteristicvalue',
            name='usage_spec_characteristic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usage.UsageSpecCharacteristic'),
        ),
    ]
